### PR TITLE
GCS: fix godep dependencies

### PR DESCRIPTION
**Pull request by aibaars**
This PR first reverts changes made to Godeps.json and Godeps/_workspace by the PR that introduced the GCS, and subsequently attempts to add the GCS dependencies the right way.

Note that the version of the google/cloud package is not the latest master but https://github.com/GoogleCloudPlatform/gcloud-golang/commit/975617b05ea8a58727e6c1a06b6161ff4185a9f2

The latest version of google/cloud has undergone some serious refactoring, and adapting the GCS driver to that should be done in a separate PR.

These are the step I performed to obtain and save the dependencies of GCS:

```
* rm -Rf Godeps/_workspace/src
* godep restore
* go get google.golang.org/cloud/storage
* cd google.golang.org/cloud/storage; git checkout 975617b05ea8a58727e6c1a06b6161ff4185a9f2
* go get google.golang.org/appengine
* godep update golang.org/x/net/context
* godep save ./...
```

### CODE REVIEW

**Comment by RichardScothern** [comment]
@aibaars out of interest, which version of godep did you use?

**Comment by aibaars** [comment]
@RichardScothern I am using "godep v46 (darwin/amd64/go1.5.2)" . It added comments and reordered some of the dependencies, so I manually editted the Godeps.json file to make the diff less chatty.

**Comment by dmp42** [comment]
Thanks @aibaars !
I'm incorporating this into https://github.com/docker/distribution/pull/1544 (rebasing will be too hairy), using your godeps.json as the basis for a `restore`.

As soon as the build is green, we should be good for a final review.

**Comment by dmp42** [comment]
@aibaars https://github.com/docker/distribution/pull/1544 is almost ready to go, and does incorporate your godeps.json changes from here.

It does build and test, but have a look at that branch if you want and let us know what you think.

Thanks again for being prompt at fixing this!

**Pull request closed without merging**
